name: Release
permissions:
  contents: read
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run archive -y
      - run: bun run .github/workflows/prerelease.ts
      - name: Check if Git tag exists
        id: check_tag
        run: echo "::set-output name=TAG::$(git tag --points-at ${{github.sha}})"
      - uses: softprops/action-gh-release@v2
        with:
          body_path: publish/release.md
          files: publish/*.zip
