name: Release
permissions:
  contents: write
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Create archive
        run: bun run archive -y
      - name: Run pre-release script
        run: bun run .github/workflows/prerelease.ts
      - name: Release tag
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          body_path: publish/release.md
          generate_release_notes: true
          files: publish/*.zip
      - name: Add latest tag as needed
        uses: EndBug/latest-tag@latest
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      - name: Release preview at latest commit
        uses: softprops/action-gh-release@v2
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          body_path: publish/release.md
          generate_release_notes: true
          files: publish/*.zip
          tag_name: latest
          make_latest: true
